version: '2'
services:
    sumfox-app:
        image: sumfox
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sumfox-postgresql:5432/sumfox
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sumfox-postgresql:
        extends:
            file: postgresql.yml
            service: sumfox-postgresql
